# fonts setup:
# install nerd font in linux / wsl (repo or download)
# fc-cache -f && fc-list
# WSL - manually install after: cp ~/.local/share/fonts/* /mnt/d/fonts/

theme = "ayu_evolve"

[editor]
true-color = true
line-number = "relative"
mouse = true
bufferline = "always"
auto-completion = true
auto-format = true
auto-save = true
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.file-picker]
hidden = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.indent-guides]
render = true
character = "â”Š" # Some characters that work well: "â–", "â”†", "â”Š", "â¸½"
skip-levels = 1

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints	= true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.statusline]
left = ["mode", "version-control", "separator", "position", "selections", "file-name", "file-modification-indicator", "spinner"]
center = ["read-only-indicator"]
right = ["diagnostics", "workspace-diagnostics"] 
separator = " îœ¥ "
mode.normal = "ğŸ§¬"
mode.insert = "ğŸ“"
mode.select = "ğŸ–ï¸"

# chained keybinds
# [keys.normal]
# nice but keybindings break after picking up a file with the external tool
# A-1 = [":new", ":insert-output tmux -c xplr", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]
