# fonts setup:
# install nerd font in linux / wsl (repo or download)
# fc-cache -f && fc-list
# WSL - manually install after: cp ~/.local/share/fonts/* /mnt/d/fonts/

theme = "tokyonight"

[editor]
true-color = true
line-number = "relative"
mouse = true
bufferline = "always"
auto-completion = true
auto-format = true
auto-save = true
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.indent-guides]
render = true
character = "â”Š" # Some characters that work well: "â–", "â”†", "â”Š", "â¸½"
skip-levels = 1

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints	= true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.statusline]
left = ["spinner", "mode", "file-type", "file-encoding", "diagnostics"]
center = ["version-control", "file-name", "read-only-indicator", "position-percentage"]
right = ["selections", "register", "position"]
separator = "â”‚"
mode.normal = "ğŸ§¬ HELIX-IS"
mode.insert = "ğŸ“ INSERT"
mode.select = "ğŸ–ï¸  SELECT"

# chained keybinds
[keys.normal]
A-1 = [":new", ":insert-output tmux -c xplr", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":redraw"]
